name: Build and Push Flask App to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t nexarsalguero/flask-app .
      - name: Push image to docker hub
        run: docker push nexarsalguero/flask-app:latest

  deploy:
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: Pull docker image
        run: sudo docker pull nexarsalguero/flask-app:latest
      - name: Delete old container
        run: sudo docker rm -f python-container  
      - name: Run docker container          
        run: sudo docker run -d -p 5000:5000 --name python-container nexarsalguero/flask-app
